name: Simple Action
on: [push]

jobs: 
  simple-action:
    runs_on: ubuntu-latest
    steps:
      - name: Simple JS Action
        id: greet
        uses: actions/hello-world-javascript-action@main
        with:
          who-to-greet: Mona the Octocat
      - name: Log Greeting TIme
        run: echo "The time was ${{ steps.greet.outputs.time }}"