# not working
name: Workflow run
on: 
  workflow_run:
    workflows: [Repository Events]
    types: [completed]
    branches:
      - main

jobs:
  echo-strin:
    runs-on: ubuntu-latest
    steps:
      - run: echo "I was triggered because 'Repository Events' workflow was completed"